<fix>(txStruct): fix bcos_sdk_encode_transaction_struct that send hex…
FISCO-BCOS/bcos-c-sdk pull request #172
Opened 2023-07-04 12:45 UTC by LucasLi1024

2023-07-04 14:10 UTC, bxq2011hust approved these changes

2023-07-05 01:47 UTC, kyonRay requested changes

2023-07-05 01:47 UTC, kyonRay commented on bcos-c-sdk/bcos_sdk_c_uti_tx_struct.cpp
> +        auto hex_tx_str = toHexStringWithPrefix(*transaction);
不应该带上hex前缀

2023-07-05 03:29 UTC, LucasLi1024 commented on bcos-c-sdk/bcos_sdk_c_uti_tx_struct.cpp
> +        auto hex_tx_str = toHexStringWithPrefix(*transaction);
目前decode 都是调用了fromHexString函数的，所以输入是否带0x都无所谓。而且局说统一下，目前都是带0x的

2023-07-05 03:32 UTC, kyonRay approved these changes

2023-07-05 04:19 UTC, JimmyShi22 approved these changes

2023-07-05 06:15 UTC, merged